### ISSUE TITLE
Add page `kind` as css class

### ISSUE THREAD

**Issue by endorama** [gokarna-theme/gokarna-hugo#114]
Hello, I would like to customize the home page, but I would like to do that without overriding the template.

I noticed that pages have a [`kind`](https://gohugo.io/templates/section-templates/) that could be used for this purpose.

What do you think about adding a class named `kind-{{.Kind}}` to the `body` tag for this purpose? I have a PR ready if you are interested!

**Comment by mansoorbarri** [comment]
I think thats personal preference. You can make a `_index.md` if you want to change the home page or just customize it by copy-pasting `/themes/layouts/index.html` to your site directory' `/layouts/index.html`

**Comment by endorama** [comment]
Hello @mansoorbarri, thank you for your answer.

I agree it's also personal preference but that's partially true. 
As of now there is no way to have CSS rules targeting a page by its type, because there are no selectors that differentiate them.

The current solution is to copy the entire layout, with the big downside that from that moment onward each update to the site default layout must be manually ported to the copy. This makes the experience of updating the theme worse.

Due to this consideration I think it is in the interest of the theme to provide the easy path here. Obviously that would support only changes through CSS, which I think is powerful enough as a default option.

No hard feelings though! ☺️

**Comment by mansoorbarri** [comment]
I mean, if you want to change CSS then just add your custom CSS to the `/assets/css`/ folder but if you want to change the content of the home page then adding `kinds` would still not update the theme at the end-user. 

From what I understand, `kinds` would take the basic layout `single.html` i.e. navbar, footer, background; but you can add your own content which would **not** sync if the theme updates the home page.

**Comment by jamesericdavidson** [comment]
@mansoorbarri has proposed some good site-level changes to address this. It may be worth adding this to the docs or a sticky issue?

Can this be closed? @endorama @526avijitgupta @yashmehrotra

**Comment by yashmehrotra** [comment]
@jamesericdavidson Yeah, I think this can be closed

For post scoped CSS changes, we can do that by having a custom css and updating markdown to use those classes

Custom kinds should be philosophically different, not cosmetically

**Comment by endorama** [comment]
I don't think I made myself clear when opening the issue, this was not about custom kinds but applying CSS to only a specific kind.

@jamesericdavidson it seems to me you mention that this is already possible. Is this documented? I didn't find guidance on this. 

> For post scoped CSS changes, we can do that by having a custom css and updating markdown to use those classes

How would this work exactly? Like adding a div with a specific class in the post/page markdown?
