### ISSUE TITLE
Can you categorize posts/* locations?

### ISSUE THREAD

**Issue by dhje0ng** [gokarna-theme/gokarna-hugo#131]
Hello sir, I have a question.
I am using the theme via hugo, When creating a markdown file for a new post, the file is located in the content/posts/* sub-path.

```
> content
 >> posts
   >>> index.md
```

However, I think this method will be very difficult to manage if there are many markdown files.
I hope the way I want it to be managed is posts/{new folder}/name.md , but I wonder if that's currently possible.

```
> content
  >> posts
   >>> 2022
    >>>> title1.md
   >>> 2021
    >>>> title2.md
```

**Comment by yashmehrotra** [comment]
Content organization is primarily managed by the hugo library, not the theme itself.

You can read more in detail about hugo's content organization at https://gohugo.io/content-management/organization/

**Comment by ramonsuarez** [comment]
Content organization is ignored by this theme. We have to set a `type: post" in each post and the theme does not recognize any posts inside a folder just because they are in the folder, which is what the Hugo doc says should happen.

**Comment by mansoorbarri** [comment]
while creating a post you can just mention the sub folders and it should work. for example if you want to create a file at `/content/posts/2023/test-1.md` you can just run the command: `hugo new posts/2023/test-1.md`

**Comment by mansoorbarri** [comment]
@dhje0ng, you can organise it according to year or even month and it will show up on the website as long as `type: post` is present in the frontmatter of the pages. Additionally, you can manage the urls by adding a `url` variable. 

For example: a file at `content/articles/2024/micro.md` will show on the website at {baseurl}/articles/2024/micro 

if you want it to show under {baseurl}/artilces/micro, add the following in `micro.md` frontmatter

```
url: "/articles/micro"
```

you can see example of this at: 
github repository: https://github.com/mansoorbarri/website/tree/c368fe30dd129c3c6b530da9796c47d2711012ad

**Comment by jamesericdavidson** [comment]
I believe this has been mitigated (#241), and I'd be happy to submit a PR which introduces more front matter (such as `slug`, as above).

Can this be closed as wontfix? @yashmehrotra @526avijitgupta
