### ISSUE TITLE
Way of not circle-cropping the avatar

### ISSUE THREAD

**Issue by fabrizio-ottati** [gokarna-theme/gokarna-hugo#152]
I would like to put an avatar which has not a circular shape (i.e. it gets cropped when displayed on the website). Are there any solutions for this? 

![image](https://user-images.githubusercontent.com/45739782/213936684-be93c091-1cb7-4cbf-a48f-e23f1fcdce16.png)

**Comment by jimlei** [comment]
I think the easiest solution would be to override the css

config.toml
 ```toml
customHeadHTML = '''
        <link rel="stylesheet" type="text/css" href="/css/site.css">
    '''
```

/static/css/site.css
```css
.header-nav .avatar img,
.home-about .avatar img {
    border-radius: 0;
}
```

This should work without any other changes. You are of course free to place the css file in whatever folder and use whichever name you please.

**Comment by mansoorbarri** [comment]
should there be a site param for this?

**Comment by jamesericdavidson** [comment]
Can this be closed? @526avijitgupta @yashmehrotra

**Comment by yashmehrotra** [comment]
@jamesericdavidson Yeah,`customHeadHTML` seems a doable solution for these scenarios
