### ISSUE TITLE
Add screenshot.py to Github Action

### ISSUE THREAD

**Issue by yashmehrotra** [gokarna-theme/gokarna-hugo#184]

**Comment by jamesericdavidson** [comment]
@yashmehrotra Is it possible for contributors to do this without having special repo permissions?

**Comment by jamesericdavidson** [comment]
- [ ] Add #262 to a GitHub action
  - [ ] Run `screenshot.py` when affected files are changed in Git

**Comment by yashmehrotra** [comment]
> @yashmehrotra Is it possible for contributors to do this without having special repo permissions?
Yeah, I think so, it would be the github workflow which would create a PR if there is a binary diff between current and newly generated images

**Comment by yashmehrotra** [comment]
Yes, @jamesericdavidson Thanks for your help in containerising the script
