### ISSUE TITLE
How to generate RSS Content instead of summary

### ISSUE THREAD

**Issue by vinay-keshava** [gokarna-theme/gokarna-hugo#192]
which xml file has to edited from <description>{{ .Summary | html }}</description>
to <description>{{ .Content | html }}</description>
so that the index.xml doesn't generate summary

**Comment by mansoorbarri** [comment]
you can't really have content of the page in `index.xml`

**Comment by mansoorbarri** [comment]
there should be a file in `/layouts/_defaults/index.rss.xml` otherwise you can create the file and define the rss file yourself

**Comment by jamesericdavidson** [comment]
@vinay-keshava Did @mansoorbarri 's solution work for you?

**Comment by vinay-keshava** [comment]
@jamesericdavidson, it did help 
Thanks (:

Closing this issue..
