### ISSUE TITLE
enhancement: update screenshots

### ISSUE THREAD

**Issue by jamesericdavidson** [gokarna-theme/gokarna-hugo#258]
[README screenshots](https://github.com/gokarna-theme/gokarna-hugo?tab=readme-ov-file#screenshots) are out of date:

- Copyright year (`now.Year`) is 2023
- [x] Update Home page screenshot
- [x] Update Posts page screenshot
  Home page and Posts page need yearly updates.
- [x] Update Documentation - Basics screenshot (#243, #233)
- ~~Replace Performance (Google Lighthouse) screenshot with higher resolution~~ Wait for #250 (#260, #261)

Low priority and good first issue.

**Comment by 526avijitgupta** [comment]
This has been pending for a long time, thanks @jamesericdavidson 

We already have a `screenshots.py` script for this purpose. I had tried running it a few weeks back but there were some errors.  
Ideally, whoever picks this up should update the `screenshot.py` script and use that to generate the updated screenshots.
cc @yashmehrotra

**Comment by jamesericdavidson** [comment]
> We already have a `screenshots.py` script for this purpose. I had tried running it a few weeks back but there were some errors.

```sh
python3 screenshot.py 
Traceback (most recent call last):
  File "/var/home/user2/Documents/Projects/gokarna/screenshot.py", line 102, in <module>
    main()
    ~~~~^^
  File "/var/home/user2/Documents/Projects/gokarna/screenshot.py", line 90, in main
    driver = webdriver.Firefox(options=options)
  File "/var/home/user2/Documents/Projects/gokarna/.virtualenvs/screenshot/lib/python3.13/site-packages/selenium/webdriver/firefox/webdriver.py", line 68, in __init__
    super().__init__(command_executor=executor, options=self.options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/user2/Documents/Projects/gokarna/.virtualenvs/screenshot/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/var/home/user2/Documents/Projects/gokarna/.virtualenvs/screenshot/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/user2/Documents/Projects/gokarna/.virtualenvs/screenshot/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/var/home/user2/Documents/Projects/gokarna/.virtualenvs/screenshot/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
```

This is the traceback I get on 3.13.0, with the dependencies installed to a `venv`:

https://github.com/gokarna-theme/gokarna-hugo/blob/5d0503b77e84cf688132a4c9cb1c7bcf44c33f18/screenshot.py#L6

```sh
mkdir .virtualenvs/
python3 -m venv .virtualenvs/screenshot
source .virtualenvs/screenshot/bin/activate
python3 -m pip install selenium==4.10.0 pillow soldier
```

I have `python3` installed via Homebrew (on Linux) which complicates things (and likely causes the browser binary error)

**Comment by jamesericdavidson** [comment]
@526avijitgupta I think we should combine this with #184, and approach this in a cloud-native fashion:

- [ ] Create a `Containerfile` (FROM Ubuntu, Alpine, etc.; which can be kept as a runner, or used as a one-shot and disposed of)
  - [ ] Install `firefox`, `python3`, and other dependencies (via the package manager)
- [ ] Test `screenshot.py` from the container
  - [ ] Fix system-specific breakages (e.g. macOS Firefox path)
- [ ] Add "run screenshot.py via container" to a GitHub action
  - [ ] Run `screenshot.py` when affected files are changed in Git
 
And so on...

**Comment by jamesericdavidson** [comment]
Narrowing the scope of this issue down - #263 will close this.

Will be tracking #262 and #184 separately, keeping the Containerfile and `screenshot.py` fixes together for portability.
