### ISSUE TITLE
Improving Google Lighthouse SEO score

### ISSUE THREAD

**Issue by 526avijitgupta** [gokarna-theme/gokarna-hugo#259]
https://github.com/gokarna-theme/gokarna-hugo/issues/250 talks about improving performance based on Google lighthouse score. Reviewing the [lightscore score](https://pagespeed.web.dev/analysis/https-gokarna-hugo-netlify-app/w90db0qrkg?form_factor=desktop), there's a scope of improving SEO to improve our visibility as a theme. 

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/13a88860-8942-45d7-b1c2-b6defaebe5cf">

<img width="1050" alt="image" src="https://github.com/user-attachments/assets/a849b93e-4a8d-40a7-b406-b8cd819e4fad">

cc @jamesericdavidson

**Comment by jamesericdavidson** [comment]
I misread the `<a>` issues as the Accessibility audits, will look at the SEO audits separately
